//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyShopQuanAo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string ID { get; set; }
        public string AccountName { get; set; }
        public string Pass { get; set; }
        public string FullName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Duty { get; set; }
        public Nullable<System.DateTime> StartingDate { get; set; }
        public string Stt { get; set; }
    }
}
