//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyShopQuanAo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductProperty
    {
        public string ID { get; set; }
        public string ProductID { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public Nullable<int> ImportNumber { get; set; }
        public Nullable<int> Remained { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
